### ISSUE TITLE
Exception is raised when call response without body method

### ISSUE THREAD

**Issue by tomas-stefano** [tomas-stefano/api_matchers#22]
ruby '2.1.2'
Rails: 4.0.8

When use the expect(response), expecting that the APIMatchers calls the 'body' method, the spec trows an exception.

```
Failure/Error: expect(response).to have_json({})
     TypeError:
       no implicit conversion of ActionController::TestResponse into String
     # /Users/tomas-stefano/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/json/common.rb:155:in `initialize'
     # /Users/tomas-stefano/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/json/common.rb:155:in `new'
     # /Users/tomas-stefano/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/json/common.rb:155:in `parse'
     # /Users/tomas-stefano/.rvm/gems/ruby-2.1.2@marketplace/gems/api_matchers-0.5.0/lib/api_matchers/core/parser.rb:5:in `json'
     # /Users/tomas-stefano/.rvm/gems/ruby-2.1.2@marketplace/gems/api_matchers-0.5.0/lib/api_matchers/response_body/have_json.rb:14:in `matches?'
     # /Users/tomas-stefano/.rvm/gems/ruby-2.1.2@marketplace/gems/rspec-expectations-2.14.5/lib/rspec/expectations/handler.rb:24:in `handle_matcher'
     # /Users/tomas-stefano/.rvm/gems/ruby-2.1.2@marketplace/gems/rspec-expectations-2.14.5/lib/rspec/expectations/expectation_target.rb:34:in `to'
```

**Comment by tomas-stefano** [comment]
Closing as solved on 1.0.0
